// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQj6Pd218nHZPirbL5yYta4smAxIy7Qjk',
    appId: '1:1026176990834:web:fbe116b64f46531a8c4ceb',
    messagingSenderId: '1026176990834',
    projectId: 'orelax-de683',
    authDomain: 'orelax-de683.firebaseapp.com',
    storageBucket: 'orelax-de683.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuucU59xA4Tx7q3bMSJdJy7rQR8Qs_TAA',
    appId: '1:1026176990834:android:ff8be6426f8514be8c4ceb',
    messagingSenderId: '1026176990834',
    projectId: 'orelax-de683',
    storageBucket: 'orelax-de683.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOViYyQXigutY6WgbyUVqWBV3MowgLAbA',
    appId: '1:1026176990834:ios:65278c5dc61191728c4ceb',
    messagingSenderId: '1026176990834',
    projectId: 'orelax-de683',
    storageBucket: 'orelax-de683.firebasestorage.app',
    iosBundleId: 'com.example.orelax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOViYyQXigutY6WgbyUVqWBV3MowgLAbA',
    appId: '1:1026176990834:ios:65278c5dc61191728c4ceb',
    messagingSenderId: '1026176990834',
    projectId: 'orelax-de683',
    storageBucket: 'orelax-de683.firebasestorage.app',
    iosBundleId: 'com.example.orelax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQj6Pd218nHZPirbL5yYta4smAxIy7Qjk',
    appId: '1:1026176990834:web:6ea30826524cd9858c4ceb',
    messagingSenderId: '1026176990834',
    projectId: 'orelax-de683',
    authDomain: 'orelax-de683.firebaseapp.com',
    storageBucket: 'orelax-de683.firebasestorage.app',
  );
}
