name: orelax
description: A secure gated community mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For smooth page indicator
  smooth_page_indicator: ^1.1.0

  # SVG support for logo and other vector assets
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.0.2
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  google_sign_in: ^6.2.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/introImg.png
    - assets/images/backgound1.jpg
    - assets/images/background2.jpg
    - assets/images/logo.svg
    - assets/icon/house.svg
    - assets/icon/message-circle.svg
    - assets/icon/user-round.svg
    - assets/icon/users.svg
    - assets/icon/triangle-alert.svg
    - assets/icon/audio-lines.svg
    - assets/icon/brick-wall-shield.svg
    - assets/icon/bell.svg
    - assets/icon/handshake.svg
    - assets/icon/languages.svg
    - assets/icon/map-pin-house.svg
    - assets/icon/moon.svg
    - assets/icon/user-pen.svg
    - assets/icon/info.svg
    - assets/icon/shield-check.svg
    - assets/icon/log-out.svg
    - assets/icon/message-circle-question-mark.svg
    - assets/images/Google_logo.svg

