name: orelax
description: A secure gated community mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  web_socket_channel: ^3.0.1
  socket_io_client: ^2.0.3
  camera: ^0.11.0
  image: ^4.2.0
  
  uuid: ^4.1.0
  # Networking & API
  http: ^1.2.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # UI & Design
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.0.2
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7
  file_picker: ^8.1.2
  share_plus: ^12.0.2
  path_provider: ^2.1.0
  url_launcher: ^6.2.0

  # Voice notes
  record: ^6.0.0
  audioplayers: ^6.1.0
  
  # State Management
  provider: ^6.1.5+1

  fl_chart: ^1.2.0
  syncfusion_flutter_charts: ^33.1.49

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/introImg.png
    - assets/images/backgound1.jpg
    - assets/images/background2.jpg
    - assets/images/logo.svg
    - assets/icon/house.svg
    - assets/images/no-message.png
    - assets/icon/message-circle.svg
    - assets/icon/user-round.svg
    - assets/icon/users.svg
    - assets/icon/thermometer-sun.svg
    - assets/icon/triangle-alert.svg
    - assets/icon/audio-lines.svg
    - assets/icon/brick-wall-shield.svg
    - assets/icon/bell.svg
    - assets/icon/handshake.svg
    - assets/icon/languages.svg
    - assets/icon/map-pin-house.svg
    - assets/icon/moon.svg
    - assets/icon/user-pen.svg
    - assets/icon/info.svg
    - assets/icon/shield-check.svg
    - assets/icon/log-out.svg
    - assets/icon/message-circle-question-mark.svg
    - assets/icon/camera.svg
    - assets/images/Google_logo.svg
    - assets/images/pool1.jpg
    - assets/images/pool2.jpg
    - assets/images/pool3.jpg
    - assets/images/pool4.jpg
    - assets/images/partyroom1.jpg
    - assets/images/partyroom2.jpg
    - assets/images/partyroom3.jpg
    - assets/images/partyroom4.jpg
    - assets/images/childcare1.jpg
    - assets/images/childcare2.jpg
    - assets/images/childcare3.jpg
    - assets/images/childcare4.jpg
    - assets/images/childcare5.jpg
    - assets/images/gym1.jpg
    - assets/images/gym2.jpg
    - assets/images/gym3.jpg
    - assets/images/gym4.jpg
    - assets/images/cleaning_staff.png
    - assets/images/electrician_staff.png
    - assets/images/plombier.png
    - assets/images/repairing.png
    - assets/images/cleaning.png
    - assets/images/electricien.png
    - assets/images/plimbierstaff.png
    - assets/images/Loginbackground.png
    - assets/images/homescreen.jpg

